# Generated by Django 4.2.3 on 2023-07-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebot', '0004_messageuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин'),
        ),
    ]
