# Generated by Django 4.2.3 on 2023-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebot', '0005_alter_tguser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
