# Generated by Django 4.2.3 on 2023-07-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebot', '0006_alter_tguser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
